-- 코드를 입력하세요
SELECT b.AUTHOR_ID, AUTHOR_NAME, CATEGORY,SUM(b.PRICE * bs.SALES) as TOTAL_SALES
from BOOK b
join AUTHOR a
on b.AUTHOR_ID = a.AUTHOR_ID
join BOOK_SALES bs
on b.BOOK_ID = bs.BOOK_ID
where bs.SALES_DATE >= '2022-01-01' and bs.SALES_DATE <= '2022-01-31'
group by b.AUTHOR_ID,CATEGORY
ORDER BY b.AUTHOR_ID asc, CATEGORY DESC