-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, count(Distinct os.USER_ID) as USERS
FROM ONLINE_SALE os
join USER_INFO ui
on os.USER_ID = ui.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR asc, MONTH asc, GENDER asc