WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1        
    FROM TIME_TABLE 
    WHERE HOUR < 23      
)

SELECT T.HOUR, count(A.ANIMAL_ID) as COUNT
FROM TIME_TABLE T
LEFT JOIN
ANIMAL_OUTS A ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR