-- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE ,'%Y-%m-%d') as REVIEW_DATE
from  REST_REVIEW rr
join MEMBER_PROFILE mp
on rr.MEMBER_ID = mp.MEMBER_ID
where mp.MEMBER_ID = 
(select MEMBER_ID
      from REST_REVIEW 
     group by MEMBER_ID
     ORDER BY COUNT(REVIEW_ID) DESC
     LIMIT 1)
order by REVIEW_DATE, REVIEW_TEXT