-- 코드를 작성해주세요
select YEAR(DIFFERENTIATION_DATE) as YEAR,(b.MAX_SIZE - a.SIZE_OF_COLONY) as YEAR_DEV ,a.ID from 
ECOLI_DATA a
join (SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
      FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE) ) b
on YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR, YEAR_DEV ASC