-- 코드를 입력하세요
SELECT CATEGORY, (PRICE) as MAX_PRICE, PRODUCT_NAME
from FOOD_PRODUCT
where (CATEGORY, PRICE) IN 
(SELECT CATEGORY, MAX(PRICE)
from food_product
group by CATEGORY
having CATEGORY LIKE '과자' or
CATEGORY LIKE '국' or
CATEGORY LIKE '김치' or
CATEGORY LIKE '식용유')
ORDER BY MAX_PRICE DESC