-- 코드를 작성해주세요
select CASE 
        WHEN (SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0) AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0 THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES where NAME LIKE 'C#') >0 THEN 'B'
        WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0 THEN 'C'
    END as GRADE, ID, EMAIL
FROM DEVELOPERS d
HAVING GRADE IS NOT NULL
order by GRADE, ID

